### ISSUE TITLE
IRSA annotation not getting applied to crossplane aws provider serviceaccount in workload cluster

### ISSUE THREAD

**Issue by iamsouravin** [aws-samples/eks-multi-cluster-gitops#32]
Problem:
The ControllerConfig annotation for Crossplane AWS Provider installed in the workload cluster is not patched and substituted by Flux `Kustomization` in `gitops-system/clusters/cluster-name/crossplane.yaml`. This is resulting in the IRSA role not getting applied to the provider serviceaccount for the AWS API calls in the workload clusters.

Fix:
The patch must be applied on the child `Kustomization` object for `crossplane-aws-provider`.

Replace
```yaml
patches:
    - target:
        group: pkg.crossplane.io
        kind: ControllerConfig
        version: v1alpha1
        name: aws-config
      patch: |-
        - op: replace
          path: /metadata/annotations
          value:
            eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/crossplane-role-cluster-name
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
```

with

```yaml
patches:
    - target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        version: v1beta2
        name: crossplane-aws-provider
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/patches
          value:
            - target:
                group: pkg.crossplane.io
                kind: ControllerConfig
                version: v1alpha1
                name: aws-config
              patch: |-
                - op: replace
                  path: /metadata/annotations
                  value:
                    eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/crossplane-role-commercial-staging
        - op: add
          path: /spec/postBuild
          value:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-info
                optional: false
```
